spring:
    data:
        rest:
            basePath: /api
            defaultPageSize: 15
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/trialdb?characterEncoding=utf8&autoReconnect=true
        username: root
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
        show-sql: true
